### ISSUE TITLE
Default parameters not getting set e.g. "Config string Retries not found" 

### ISSUE THREAD

**Issue by RocklinSoftware** [PitneyBowes/pitneybowes-shipping-api-csharp#24]
Hi PB,

I removed the NuGet package and added the SDK to my VS2017 console project to get needed SDK features into my software; package!=SDK. I had to add the following Session configuration to get the shippingapi to work.

Are RecordRoot and RecordPath  the same? 

            session.AddConfigItem("Retries", "3");
            session.AddConfigItem("RecordAPICalls", "true");
            session.AddConfigItem("RecordRoot", ".");
            session.AddConfigItem("RecordOverwrite", "false");
            session.AddConfigItem("ThrowExceptions", "false");

        /// Default parameters
        ///     Record = false;
        ///     RecordPath = Globals.GetPath(Path.GetTempPath(), "recordings", "shippingApi");
        ///     RecordOverwrite = false;
        ///     Retries = 3;
        ///     UserAgent = "Pitney Bowes CSharp SDK 1.0";
        ///     ThrowExceptions = false;

Thank you,
David Stemkoski

**Comment by pa009fa** [comment]
Hi David,

Sorry it is confusing but RecordPath and RecordRoot are the same:

        /// <summary>

        /// Path for the recording files.

        /// </summary>

        public string RecordPath {

            get => GetConfigItem("RecordRoot") ??  _recordPath;

            set => _recordPath = value;

        }

Note if you have recording on you will get a log of requests to and responses from the server. This will fill up the disk eventually. The feature is there because a log of production traffic can be useful for various things. Also the SDK has the ability to replay from the log file, so you could sample production traffic and replay in your QA environment, for instance.

Regards.

**Comment by pa009fa** [comment]
David,

Regarding IrregularParcelGirth in the fluent method. It isn’t in production yet. Do I understand correctly that you are using the source code form github? If so, I can push that fix or you could patch it yourself (if you are interested). I’m happy to review and incorporate pull requests also.

This is the change I was going to make in parcelfluent.cs, line 62.

        public ParcelFluent<T> Dimension(decimal l, decimal h, decimal w, UnitOfDimension u = UnitOfDimension.IN, decimal g = 0)
        {
            _parcel.Dimension = new ParcelDimension() { Length = l, Height = h, Width = w, UnitOfMeasurement = u, IrregularParcelGirth = g };
            return this;
        }


From: Patrick Farry <Patrick.Farry@pb.com>
Date: Thursday, February 21, 2019 at 8:33 AM
To: PitneyBowes/pitneybowes-shipping-api-csharp <reply@reply.github.com>, PitneyBowes/pitneybowes-shipping-api-csharp <pitneybowes-shipping-api-csharp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [PitneyBowes/pitneybowes-shipping-api-csharp] Default parameters not getting set e.g. "Config string Retries not found" (#24)

Hi David,

Sorry it is confusing but RecordPath and RecordRoot are the same:

        /// <summary>

        /// Path for the recording files.

        /// </summary>

        public string RecordPath {

            get => GetConfigItem("RecordRoot") ??  _recordPath;

            set => _recordPath = value;

        }

Note if you have recording on you will get a log of requests to and responses from the server. This will fill up the disk eventually. The feature is there because a log of production traffic can be useful for various things. Also the SDK has the ability to replay from the log file, so you could sample production traffic and replay in your QA environment, for instance.

Regards.

**Comment by RocklinSoftware** [comment]
Hi,

Yes go ahead and push the update. I will update my side code. It is never a
problem, updating is easy. I am working through the code base.

Thanks,
David Stemkoski

**Comment by pa009fa** [comment]
Pushed the change.
